/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
export interface FacebookAuth {
  facebook_access_token?: string | null;
  facebook_auth_id: string;
  id?: number;
  user_id?: number | null;
}
export interface SoptUser {
  bio: string;
  id?: number;
  name: string;
}
